;;;; Autogenerated ASD file for system "ALIEN.TEST"
;;;; In order to regenerate it, run update-asdf
;;;; from shell (see https://github.com/phoe-krk/asd-generator)
;;;; For those who do not have update-asdf,
;;;; run `ros install asd-generator` (if you have roswell installed)
;;;; There are also an interface available from lisp:
;;;; (asd-generator:regen &key im-sure)
(defsystem alien.test
 :author "Masataro Asai"
 :mailto "guicho2.71828@gmail.com"
 :description "Test system of alien"
 :license "LLGPL"
 :depends-on (:alien
              :fiveam
              :bordeaux-threads
              :lparallel
              :cl-cpus
              :cl-rlimit)
 :serial t
 :components ((:module "t"
               :components ((:file "package")
                            (:file "instantiate")
                            (:file "solve"))))
 :defsystem-depends-on (:trivial-package-manager)
 :perform
 (load-op :before (op c)
          (uiop:symbol-call :trivial-package-manager
                            :ensure-program
                            "validate"
                            :env-alist `(("PATH" . ,(format nil "~a:~a"
                                                            (asdf:system-relative-pathname :alien "VAL/")
                                                            (uiop:getenv "PATH"))))
                            :from-source (format nil "cd ~a; git clone https://github.com/guicho271828/VAL.git; cd ~a ; make validate"
                                                 (asdf:system-source-directory :alien)
                                                 (asdf:system-relative-pathname :alien "VAL/")))
          (uiop:symbol-call :trivial-package-manager
                            :ensure-program
                            "fast-downward.py"
                            :env-alist `(("PATH" . ,(format nil "~a:~a"
                                                            (asdf:system-relative-pathname :alien "downward/")
                                                            (uiop:getenv "PATH"))))
                            :from-source (format nil "cd ~a; git clone https://github.com/guicho271828/FastDownward.git downward; cd ~a ; ./build.py"
                                                 (asdf:system-source-directory :alien)
                                                 (asdf:system-relative-pathname :alien "downward/"))))
 :perform
 (test-op :after (op c)
          (eval (read-from-string "(5am:run! :alien)"))))
