;;;; Autogenerated ASD file for system "STRIPS.TEST"
;;;; In order to regenerate it, run update-asdf
;;;; from shell (see https://github.com/phoe-krk/asd-generator)
;;;; For those who do not have update-asdf,
;;;; run `ros install asd-generator` (if you have roswell installed)
;;;; There are also an interface available from lisp:
;;;; (asd-generator:regen &key im-sure)
(defsystem strips.test
 :author "Masataro Asai"
 :mailto "guicho2.71828@gmail.com"
 :description "Test system of strips"
 :license "LLGPL"
 :depends-on (:strips
              :fiveam
              :bordeaux-threads
              :lparallel
              :cl-cpus)
 :serial t
 :components ((:module "t"
               :components ((:file "package")
                            (:file "instantiate"))))
 :perform (test-op :after (op c)
           (eval (read-from-string "(5am:run! :strips)"))))
